FROM node:20-slim

RUN apt-get update && apt-get install -y --no-install-recommends tini && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .

WORKDIR /app/server/node

RUN touch /app/.env && echo "NODE_ENV=production" >> /app/.env

ENTRYPOINT ["/usr/bin/tini", "--"]

EXPOSE 3001

CMD sh -c "npm run dev:backend"